### PR TITLE
Fix bug in freeing geo polygon memory

### LINKED ISSUE #103: Inconsistent results from polyfill after calling polyfill with complex polygon crossing antimeridian
It seems that calling `polyfill` with a complex polygon (that crosses the antimeridian) messes with the h3 internals somehow, causing subsequent calls to return incorrect results.

This is best demonstrated by this jsfiddle: https://jsfiddle.net/tamaxerra/kxz865m7/1/

The console output from the fiddle is the number of h3 indexes returned:
```
36
56
27
```

The first (36) and last (27) count are the result of the same polygon being passed.

### PR DESCRIPTION
**Pull request by nrabinowitz**
Closes #103 

This fixes some errors in freeing `GeoPolygon` memory, which could get the Emscripten virtual memory management into a bad state. 

Explanation of the issue: We were expecting the `GeoPolygon` reference to `Geofence` to be a pointer, but it’s not, the struct is inlined into `GeoPolygon`. So I was trying to free the value at the geofence position, because I thought it was a pointer, but I’m actually getting the first value in the Geofence struct, which is `numVerts`, and trying to free that. C would probably segfault at this point, Emscripten just gets confused and ends up with undefined behavior in future calls.

### CODE REVIEW

File: lib/h3core.js [hunk 1]
```diff
@@ -245,12 +245,15 @@ function destroyGeoPolygon(geoPolygon) {
     const geofenceOffset = 0;
     const numHolesOffset = geofenceOffset + SZ_GEOFENCE;
     const holesOffset = numHolesOffset + SZ_INT;
-    // Free the outer loop
-    C._free(C.getValue(geoPolygon + geofenceOffset, 'i8*'));
-    // Free the holes, if any
+    // Offset of the geofence vertex array pointer within the Geofence struct
+    const geofenceArrayOffset = SZ_INT;
+    // Free the outer vertex array
+    C._free(C.getValue(geoPolygon + geofenceOffset + geofenceArrayOffset, 'i8*'));
```
Comment (nrabinowitz) [inline lib/h3core.js:251]: This was the main issue, including the `geofenceArrayOffset` when looking up the vertex array pointer.

File: lib/h3core.js [hunk 2]
```diff
@@ -245,12 +245,15 @@ function destroyGeoPolygon(geoPolygon) {
...
+    // Free the vertex array for the holes, if any
     const numHoles = C.getValue(geoPolygon + numHolesOffset, 'i32');
+    const holes = C.getValue(geoPolygon + holesOffset, 'i32');
     for (let i = 0; i < numHoles; i++) {
-        C._free(C.getValue(geoPolygon + holesOffset + SZ_GEOFENCE * i, 'i8*'));
+        C._free(C.getValue(holes + SZ_GEOFENCE * i + geofenceArrayOffset, 'i8*'));
```
Comment (nrabinowitz) [inline lib/h3core.js:256]: I couldn't find a test case that showed the issue, but this was pretty incorrect - we weren't looking up the holes in the right way at all.

Do I need to free `holes` here too? It seems like I might...

Comment (nrabinowitz) [reply lib/h3core.js]: Updates to free `holes`

Comment (dfellis) [reply lib/h3core.js]: Yeah, you need to free the holes, [they're a pointer in the GeoPolygon struct](https://github.com/uber/h3/blob/master/src/h3lib/include/h3api.h.in#L104-L111)

File: lib/h3core.js [hunk 3]
```diff
@@ -251,9 +251,12 @@ function destroyGeoPolygon(geoPolygon) {
...
     const numHoles = C.getValue(geoPolygon + numHolesOffset, 'i32');
-    const holes = C.getValue(geoPolygon + holesOffset, 'i32');
-    for (let i = 0; i < numHoles; i++) {
-        C._free(C.getValue(holes + SZ_GEOFENCE * i + geofenceArrayOffset, 'i8*'));
+    if (numHoles > 0) {
+        const holes = C.getValue(geoPolygon + holesOffset, 'i32');
+        for (let i = 0; i < numHoles; i++) {
+            C._free(C.getValue(holes + SZ_GEOFENCE * i + geofenceArrayOffset, 'i8*'));
+        }
+        C._free(holes);
```
Comment (dfellis) [inline lib/h3core.js:259]: Don't you need to go into each `hole` struct and free the inner coordinates array, too?

File: test/h3core.spec.js [hunk 4]
```diff
@@ -663,6 +663,43 @@ test('polyfill - BBox corners (#67)', assert => {
...
+    for (let i = 0; i < numVerts; i++) {
+        const theta = interval * i;
+        polygon.push([radius * Math.cos(theta), radius * Math.sin(theta)]);
+    }
+    return polygon;
+}
+
+test('polyfill - memory management bug (#103)', assert => {
+    // Note that when this memory mangement issue occurs, it makes a number of *other* tests fail.
+    // Unfortunately this test itself doesn't seem to fail, though the
```
Comment (isaacbrodsky) [inline test/h3core.spec.js:679]: comment got cut off?

**Review by isaacbrodsky — APPROVED** [review]
Are there any ways to test for this class of bugs? For example is there an equivalent to Valgrind that can be used to check that the allocated/freed buffers match up?

File: lib/h3core.js (hunk 3 above)
Comment (nrabinowitz) [reply lib/h3core.js:259]: That's what L257 does - gets the array pointer for each hole and frees it

File: test/h3core.spec.js (hunk 4 above)
Comment (nrabinowitz) [reply test/h3core.spec.js:679]: Whoops, will fix

**Comment by nrabinowitz** [comment]
> Are there any ways to test for this class of bugs? For example is there an equivalent to Valgrind that can be used to check that the allocated/freed buffers match up?

I honestly don't know. The memory starts off clean, so all of the issues are deterministic. The original test case (the pair of polygons in #103) was deterministic, so I could test via script and determine whether the counts matched or not. The test I put into the test suite was deterministic too, but not in the way I'd like - if it mismanaged the memory, that test still passed, but 23 other subsequent tests failed with weird behavior. But I doubt there's any Valgrind equivalent just for Emscripten-compiled code :/.

File: lib/h3core.js (hunk 3 above)
Comment (dfellis) [reply lib/h3core.js:259]: Bleh, I clearly shouldn't be reviewing C-memory-management-in-JS code while also working on my own code. Somehow I thought the loop was the outer array being deallocated.

**Review by dfellis — APPROVED** [review]
